# CMake generated Testfile for 
# Source directory: /Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics
# Build directory: /Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(metrics.ValueObserver.Observe "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=ValueObserver.Observe")
set_tests_properties(metrics.ValueObserver.Observe PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.SumObserver.DefaultConstruction "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=SumObserver.DefaultConstruction")
set_tests_properties(metrics.SumObserver.DefaultConstruction PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.UpDownSumObserver.DefaultConstruction "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=UpDownSumObserver.DefaultConstruction")
set_tests_properties(metrics.UpDownSumObserver.DefaultConstruction PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.Counter.DefaultConstruction "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=Counter.DefaultConstruction")
set_tests_properties(metrics.Counter.DefaultConstruction PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.Counter.Add "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=Counter.Add")
set_tests_properties(metrics.Counter.Add PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.UpDownCounter.DefaultConstruction "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=UpDownCounter.DefaultConstruction")
set_tests_properties(metrics.UpDownCounter.DefaultConstruction PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.UpDownCounter.Add "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=UpDownCounter.Add")
set_tests_properties(metrics.UpDownCounter.Add PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.ValueRecorder.DefaultConstruction "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=ValueRecorder.DefaultConstruction")
set_tests_properties(metrics.ValueRecorder.DefaultConstruction PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.ValueRecorder.Record "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_instrument_test" "--gtest_filter=ValueRecorder.Record")
set_tests_properties(metrics.ValueRecorder.Record PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.Provider.GetMeterProviderDefault "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/meter_provider_test" "--gtest_filter=Provider.GetMeterProviderDefault")
set_tests_properties(metrics.Provider.GetMeterProviderDefault PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.Provider.SetMeterProvider "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/meter_provider_test" "--gtest_filter=Provider.SetMeterProvider")
set_tests_properties(metrics.Provider.SetMeterProvider PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.Provider.MultipleMeterProviders "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/meter_provider_test" "--gtest_filter=Provider.MultipleMeterProviders")
set_tests_properties(metrics.Provider.MultipleMeterProviders PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.NoopTest.CreateInstruments "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_metrics_test" "--gtest_filter=NoopTest.CreateInstruments")
set_tests_properties(metrics.NoopTest.CreateInstruments PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
add_test(metrics.NoopMeter.RecordBatch "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/noop_metrics_test" "--gtest_filter=NoopMeter.RecordBatch")
set_tests_properties(metrics.NoopMeter.RecordBatch PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;5;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/api/test/metrics/CMakeLists.txt;0;")
