# CMake generated Testfile for 
# Source directory: /Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http
# Build directory: /Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ext.http.curl.BasicCurlHttpTests.DoNothing "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/curl_http_test" "--gtest_filter=BasicCurlHttpTests.DoNothing")
set_tests_properties(ext.http.curl.BasicCurlHttpTests.DoNothing PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;9;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;0;")
add_test(ext.http.curl.BasicCurlHttpTests.HttpRequest "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/curl_http_test" "--gtest_filter=BasicCurlHttpTests.HttpRequest")
set_tests_properties(ext.http.curl.BasicCurlHttpTests.HttpRequest PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;9;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;0;")
add_test(ext.http.curl.BasicCurlHttpTests.HttpResponse "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/curl_http_test" "--gtest_filter=BasicCurlHttpTests.HttpResponse")
set_tests_properties(ext.http.curl.BasicCurlHttpTests.HttpResponse PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;9;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;0;")
add_test(ext.http.curl.BasicCurlHttpTests.SendGetRequest "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/curl_http_test" "--gtest_filter=BasicCurlHttpTests.SendGetRequest")
set_tests_properties(ext.http.curl.BasicCurlHttpTests.SendGetRequest PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;9;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;0;")
add_test(ext.http.curl.BasicCurlHttpTests.SendPostRequest "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/curl_http_test" "--gtest_filter=BasicCurlHttpTests.SendPostRequest")
set_tests_properties(ext.http.curl.BasicCurlHttpTests.SendPostRequest PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;9;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;0;")
add_test(ext.http.curl.BasicCurlHttpTests.RequestTimeout "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/curl_http_test" "--gtest_filter=BasicCurlHttpTests.RequestTimeout")
set_tests_properties(ext.http.curl.BasicCurlHttpTests.RequestTimeout PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;9;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;0;")
add_test(ext.http.curl.BasicCurlHttpTests.CurlHttpOperations "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/curl_http_test" "--gtest_filter=BasicCurlHttpTests.CurlHttpOperations")
set_tests_properties(ext.http.curl.BasicCurlHttpTests.CurlHttpOperations PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;9;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/ext/test/http/CMakeLists.txt;0;")
