cc_test(
    name = "logger_provider_test",
    srcs = [
        "logger_provider_test.cc",
    ],
    deps = [
        "//api",
        "//sdk/src/logs",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "logger_test",
    srcs = [
        "logger_test.cc",
    ],
    deps = [
        "//sdk/src/logs",
        "//sdk/src/trace",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "simple_log_processor_test",
    srcs = [
        "simple_log_processor_test.cc",
    ],
    deps = [
        "//sdk/src/logs",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "simple_log_processor_test",
    srcs = [
        "simple_log_processor_test.cc",
    ],
    deps = [
        "//sdk/src/logs",
        "@com_google_googletest//:gtest_main",
    ],
)
