# CMake generated Testfile for 
# Source directory: /Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream
# Build directory: /Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(exporter.OStreamMetricsExporter.PrintCounter "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_metrics_test" "--gtest_filter=OStreamMetricsExporter.PrintCounter")
set_tests_properties(exporter.OStreamMetricsExporter.PrintCounter PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;18;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamMetricsExporter.PrintMinMaxSumCount "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_metrics_test" "--gtest_filter=OStreamMetricsExporter.PrintMinMaxSumCount")
set_tests_properties(exporter.OStreamMetricsExporter.PrintMinMaxSumCount PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;18;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamMetricsExporter.PrintGauge "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_metrics_test" "--gtest_filter=OStreamMetricsExporter.PrintGauge")
set_tests_properties(exporter.OStreamMetricsExporter.PrintGauge PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;18;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamMetricsExporter.PrintExact "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_metrics_test" "--gtest_filter=OStreamMetricsExporter.PrintExact")
set_tests_properties(exporter.OStreamMetricsExporter.PrintExact PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;18;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamMetricsExporter.PrintHistogram "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_metrics_test" "--gtest_filter=OStreamMetricsExporter.PrintHistogram")
set_tests_properties(exporter.OStreamMetricsExporter.PrintHistogram PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;18;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamMetricsExporter.PrintSketch "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_metrics_test" "--gtest_filter=OStreamMetricsExporter.PrintSketch")
set_tests_properties(exporter.OStreamMetricsExporter.PrintSketch PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;18;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamSpanExporter.Shutdown "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_span_test" "--gtest_filter=OStreamSpanExporter.Shutdown")
set_tests_properties(exporter.OStreamSpanExporter.Shutdown PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;20;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamSpanExporter.PrintDefaultSpan "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_span_test" "--gtest_filter=OStreamSpanExporter.PrintDefaultSpan")
set_tests_properties(exporter.OStreamSpanExporter.PrintDefaultSpan PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;20;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamSpanExporter.PrintChangedSpanCout "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_span_test" "--gtest_filter=OStreamSpanExporter.PrintChangedSpanCout")
set_tests_properties(exporter.OStreamSpanExporter.PrintChangedSpanCout PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;20;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamSpanExporter.PrintChangedSpanCerr "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_span_test" "--gtest_filter=OStreamSpanExporter.PrintChangedSpanCerr")
set_tests_properties(exporter.OStreamSpanExporter.PrintChangedSpanCerr PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;20;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
add_test(exporter.OStreamSpanExporter.PrintChangedSpanClog "/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/ostream_span_test" "--gtest_filter=OStreamSpanExporter.PrintChangedSpanClog")
set_tests_properties(exporter.OStreamSpanExporter.PrintChangedSpanClog PROPERTIES  _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/GoogleTest.cmake;378;add_test;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;20;gtest_add_tests;/Users/mseufert/Documents/opentelemetry-cpp-ES-exporter/exporters/ostream/CMakeLists.txt;0;")
